// Builds the seed SQL for a program block. Idempotent: upserts by natural key
// (slug / key / block+day / block+week+day).

import type { ProgramBlock } from "../lib/training/types";

type SqlValue = string | number | boolean | null | number[];

function lit(v: SqlValue): string {
  if (v === null) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (Array.isArray(v)) return `'{${v.join(",")}}'::int[]`;
  return `'${v.replace(/'/g, "''")}'`;
}

const row = (values: SqlValue[]) => `  (${values.map(lit).join(", ")})`;

export function buildSeed(block: ProgramBlock): string {
  const out: string[] = [];
  const blockRef = `(select id from public.program_blocks where slug = ${lit(block.slug)})`;

  out.push(`-- Generated by scripts/generate-seed.ts. Do not edit by hand.`);
  out.push(`begin;`, ``);

  out.push(`insert into public.program_blocks (slug, name, description, duration_weeks, deload_weeks, is_active) values`);
  out.push(row([block.slug, block.name, block.description, block.durationWeeks, block.deloadWeeks, true]));
  out.push(`on conflict (slug) do update set name = excluded.name, description = excluded.description,`);
  out.push(`  duration_weeks = excluded.duration_weeks, deload_weeks = excluded.deload_weeks, is_active = excluded.is_active;`);
  out.push(``);

  out.push(`insert into public.exercises (slug, name, category, load_type, load_direction, image_url, video_url, animation_url, instructions) values`);
  out.push(
    block.exercises
      .map((e) => row([e.slug, e.name, e.category, e.loadType, e.loadDirection, e.imageUrl, e.videoUrl, e.animationUrl, e.instructions]))
      .join(",\n"),
  );
  out.push(`on conflict (slug) do update set name = excluded.name, category = excluded.category,`);
  out.push(`  load_type = excluded.load_type, load_direction = excluded.load_direction, image_url = excluded.image_url,`);
  out.push(`  video_url = excluded.video_url, animation_url = excluded.animation_url, instructions = excluded.instructions;`);
  out.push(``);

  out.push(`insert into public.program_days (program_block_id, day_of_week, name, full_name, session_type, notes, sort_order)`);
  out.push(`select ${blockRef}, v.* from (values`);
  out.push(block.days.map((d) => row([d.dayOfWeek, d.name, d.fullName, d.sessionType, d.notes, d.dayOfWeek])).join(",\n"));
  out.push(`) as v (day_of_week, name, full_name, session_type, notes, sort_order)`);
  out.push(`on conflict (program_block_id, day_of_week) do update set name = excluded.name, full_name = excluded.full_name,`);
  out.push(`  session_type = excluded.session_type, notes = excluded.notes, sort_order = excluded.sort_order;`);
  out.push(``);

  const prescriptions = block.days.flatMap((d) => d.prescriptions.map((p) => ({ d, p })));
  out.push(`insert into public.exercise_prescriptions (key, program_day_id, exercise_id, section, sort_order, sets, sets_max,`);
  out.push(`  rep_min, rep_max, duration_seconds, duration_seconds_max, per_side, rest_seconds, target_rir_min, target_rir_max,`);
  out.push(`  progression_type, load_increment, notes, is_optional)`);
  out.push(`select v.key, pd.id, e.id, v.section, v.sort_order, v.sets, v.sets_max, v.rep_min, v.rep_max, v.duration_seconds,`);
  out.push(`  v.duration_seconds_max, v.per_side, v.rest_seconds, v.target_rir_min, v.target_rir_max, v.progression_type,`);
  out.push(`  v.load_increment, v.notes, v.is_optional`);
  out.push(`from (values`);
  out.push(
    prescriptions
      .map(({ d, p }) =>
        row([
          p.key, d.dayOfWeek, p.exerciseSlug, p.section, p.sortOrder, p.sets, p.setsMax, p.repMin, p.repMax,
          p.durationSeconds, p.durationSecondsMax, p.perSide, p.restSeconds, p.targetRirMin, p.targetRirMax,
          p.progressionType, p.loadIncrement, p.notes, p.isOptional,
        ]),
      )
      .join(",\n"),
  );
  out.push(`) as v (key, day_of_week, exercise_slug, section, sort_order, sets, sets_max, rep_min, rep_max, duration_seconds,`);
  out.push(`  duration_seconds_max, per_side, rest_seconds, target_rir_min, target_rir_max, progression_type, load_increment,`);
  out.push(`  notes, is_optional)`);
  out.push(`join public.program_days pd on pd.program_block_id = ${blockRef} and pd.day_of_week = v.day_of_week`);
  out.push(`join public.exercises e on e.slug = v.exercise_slug`);
  out.push(`on conflict (key) do update set program_day_id = excluded.program_day_id, exercise_id = excluded.exercise_id,`);
  out.push(`  section = excluded.section, sort_order = excluded.sort_order, sets = excluded.sets, sets_max = excluded.sets_max,`);
  out.push(`  rep_min = excluded.rep_min, rep_max = excluded.rep_max, duration_seconds = excluded.duration_seconds,`);
  out.push(`  duration_seconds_max = excluded.duration_seconds_max, per_side = excluded.per_side,`);
  out.push(`  rest_seconds = excluded.rest_seconds, target_rir_min = excluded.target_rir_min,`);
  out.push(`  target_rir_max = excluded.target_rir_max, progression_type = excluded.progression_type,`);
  out.push(`  load_increment = excluded.load_increment, notes = excluded.notes, is_optional = excluded.is_optional;`);
  out.push(``);

  out.push(`insert into public.cardio_prescriptions (program_block_id, week_number, day_of_week, modality, target_minutes,`);
  out.push(`  target_minutes_max, target_rpe_min, target_rpe_max, notes)`);
  out.push(`select ${blockRef}, v.* from (values`);
  out.push(
    block.cardio
      .map((c) => row([c.weekNumber, c.dayOfWeek, c.modality, c.targetMinutes, c.targetMinutesMax, c.targetRpeMin, c.targetRpeMax, c.notes]))
      .join(",\n"),
  );
  out.push(`) as v (week_number, day_of_week, modality, target_minutes, target_minutes_max, target_rpe_min, target_rpe_max, notes)`);
  out.push(`on conflict (program_block_id, week_number, day_of_week) do update set modality = excluded.modality,`);
  out.push(`  target_minutes = excluded.target_minutes, target_minutes_max = excluded.target_minutes_max,`);
  out.push(`  target_rpe_min = excluded.target_rpe_min, target_rpe_max = excluded.target_rpe_max, notes = excluded.notes;`);
  out.push(``);

  out.push(`commit;`, ``);
  return out.join("\n");
}
