// Exercise illustrations from Everkinetic (https://github.com/everkinetic/data), CC BY-SA 4.0.
// Each entry maps our exercise slug to an Everkinetic exercise id (two frames: relaxation, tension).
// Only exact or clearly equivalent movements are mapped; anything else keeps a neutral placeholder,
// because a wrong demonstration is worse than none. Files are generated by
// scripts/fetch-exercise-media.ts into public/exercise-media/.

export interface MediaSource {
  everkineticId: string; // e.g. "0042"
  match: "exact" | "close";
  /** Only use the first frame (e.g. a hang), no loop. */
  stillOnly?: boolean;
}

export const MEDIA_MAP: Record<string, MediaSource> = {
  // exact
  "bench-press": { everkineticId: "0042", match: "exact" },
  "paused-bench-press": { everkineticId: "0042", match: "exact" },
  "pull-up": { everkineticId: "0087", match: "exact" },
  "strict-pull-up": { everkineticId: "0087", match: "exact" },
  dip: { everkineticId: "0054", match: "exact" },
  "incline-db-press": { everkineticId: "0080", match: "exact" },
  "seated-cable-row": { everkineticId: "0025", match: "exact" },
  "lateral-raise": { everkineticId: "0018", match: "exact" },
  "rear-delt-fly": { everkineticId: "0032", match: "exact" },
  "triceps-pressdown": { everkineticId: "0205", match: "exact" },
  "incline-db-curl": { everkineticId: "0214", match: "exact" },
  "preacher-curl": { everkineticId: "0236", match: "exact" },
  "hammer-curl": { everkineticId: "0227", match: "exact" },
  "leg-press": { everkineticId: "0127", match: "exact" },
  "romanian-deadlift": { everkineticId: "0118", match: "exact" },
  "reverse-lunge": { everkineticId: "0129", match: "exact" },
  "seated-calf-raise": { everkineticId: "0279", match: "exact" },
  "hack-squat": { everkineticId: "0123", match: "exact" },
  "leg-curl": { everkineticId: "0119", match: "exact" },
  "leg-extension": { everkineticId: "0142", match: "exact" },
  "standing-calf-raise": { everkineticId: "0282", match: "exact" },
  "back-extension": { everkineticId: "0103", match: "exact" },
  // close: same movement pattern, different grip/implement/setup
  "lat-pulldown": { everkineticId: "0093", match: "close" },
  "chest-supported-row": { everkineticId: "0029", match: "close" },
  "reverse-pec-deck": { everkineticId: "0032", match: "close" },
  "overhead-cable-triceps-extension": { everkineticId: "0164", match: "close" },
  "cable-lateral-raise": { everkineticId: "0018", match: "close" },
  "heel-elevated-goblet-squat": { everkineticId: "0130", match: "close" },
  "bulgarian-split-squat": { everkineticId: "0147", match: "close" },
  "hip-thrust": { everkineticId: "0109", match: "close" },
  "dead-hang": { everkineticId: "0087", match: "close", stillOnly: true },
};

export function mediaUrls(slug: string): { imageUrl: string | null; animationUrl: string | null } {
  const m = MEDIA_MAP[slug];
  if (!m) return { imageUrl: null, animationUrl: null };
  return {
    imageUrl: `/exercise-media/${slug}.svg`,
    animationUrl: m.stillOnly ? null : `/exercise-media/${slug}-loop.svg`,
  };
}
